### ISSUE TITLE
源代码打包不成功，能指导我下吗 我用的node版本是12，node用最新的版本又各种报错

### ISSUE THREAD

**Issue by manry11** [liyang5945/sync-player#1]
![image](https://user-images.githubusercontent.com/14146971/139026962-7bcdad4e-b394-499e-8f95-3e9c51cc327d.png)

**Comment by liyang5945** [comment]
你这看起来是依赖包都没安装成功，使用官方npm源，不要使用淘宝npm源或cnpm

**Comment by manry11** [comment]
好的，node版本有关系吗，你那边node版本是多少呀

**Comment by manry11** [comment]
NODE版本用的是多少？

**Comment by liyang5945** [comment]
> 
> 
> NODE版本用的是多少？

12及以上都可以

**Comment by manry11** [comment]
现在 run dev 能跑通了，最终的打包还是不行，能帮我看下吗

**Comment by manry11** [comment]
<img width="531" alt="f90bdb10fab02899fc202cbbf911274" src="https://user-images.githubusercontent.com/14146971/139048536-0d43cc2b-092b-4692-b968-5812d18f033d.png">

**Comment by manry11** [comment]
能打包了，谢谢了
