### ISSUE TITLE
请求把main.js在三种不同方案下的使用分开写三个文件

### ISSUE THREAD

**Issue by citronsky** [liyang5945/sync-player#10]
很喜欢作者的这个项目，但不是很懂js，请求作者可以写得更加让小白明白一点傻瓜式设置，感激不尽

**Comment by liyang5945** [comment]
新的代码添加了详细的注释，至于其他的我无能为力，你自己多学习吧，怎么开启一个本地服务器，怎么安装nodejs启动一个本地服务
