### ISSUE TITLE
想问一下web版如何添加本地视频

### ISSUE THREAD

**Issue by 123de234** [liyang5945/sync-player#12]

**Comment by liyang5945** [comment]
使用nginx启动一个本地服务器，映射二级目录到一个文件夹，设为索引模式，里面放视频文件，访问这个二级目录时可以看到所有的文件，右键复制视频链接到那个输入框就行了，给你看下我的nginx配置：
```
location / {
            root   D:/nginx_root;
            index  index.html index.htm;
        }
location ^~/movie {
            root   E:/Downloads;
            autoindex on;
            autoindex_format html;
            autoindex_exact_size on;
            autoindex_localtime on; 
        }
```
访问后是这样的，右键即可复制链接，例: http://192.168.3.58:8088/movie/sp1.m4v

![2022-10-14 13 49 42](https://user-images.githubusercontent.com/23631026/195772012-485cbfcd-4bd6-4e16-928e-8f22622509ec.png)
