### ISSUE TITLE
leancloud还可以正常使用吗？

### ISSUE THREAD

**Issue by wangx2** [liyang5945/sync-player#13]
找到ID跟key填写到了main.js里面，用浏览器访问了页面，但是leancloud并没有获取到即时通讯下“对话”的那个ID

**Comment by liyang5945** [comment]
> 找到ID跟key填写到了main.js里面，用浏览器访问了页面，但是leancloud并没有获取到即时通讯下“对话”的那个ID

可以正常使用，下面的REST API 服务器地址也要复制进去

**Comment by wangx2** [comment]
> > 找到ID跟key填写到了main.js里面，用浏览器访问了页面，但是leancloud并没有获取到即时通讯下“对话”的那个ID
> 
> 可以正常使用，下面的REST API 服务器地址也要复制进去

我把那个地址也填写了呢，也并没有获取到

**Comment by liyang5945** [comment]
代码你确定改对了吗，在main.js 26~28行
![2022_10_26_09_29_20](https://user-images.githubusercontent.com/23631026/197913907-c6e5e326-2b4a-4743-bc36-2cf6c23bdeb0.jpg)
改完用浏览器打开页面，leancloud控制台里就会出现一个新的对话
![2022-10-26 09 32 21](https://user-images.githubusercontent.com/23631026/197913916-05ed1efa-8ac8-472e-a986-5466e5bc34cf.png)

**Comment by wangx2** [comment]
> 代码你确定改对了吗，在main.js 26~28行 ![2022_10_26_09_29_20](https://user-images.githubusercontent.com/23631026/197913907-c6e5e326-2b4a-4743-bc36-2cf6c23bdeb0.jpg) 改完用浏览器打开页面，leancloud控制台里就会出现一个新的对话 ![2022-10-26 09 32 21](https://user-images.githubusercontent.com/23631026/197913916-05ed1efa-8ac8-472e-a986-5466e5bc34cf.png)

谢谢了，我知道哪里的问题了，我注册的国际版本，国际版本域名好像不给内地提供，我绑定了自己的域名就可以了。
感谢了！
