### ISSUE TITLE
请问可以增加对m3u8的支持吗

### ISSUE THREAD

**Issue by eocene317** [liyang5945/sync-player#3]

**Comment by liyang5945** [comment]
可以，你提供几个m3u8的视频地址我来测试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liyang5945/sync-player"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月18日(星期二) 下午4:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[liyang5945/sync-player] 请问可以增加对m3u8的支持吗 (Issue #3)





 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liyang5945** [comment]
已经添加
