### ISSUE TITLE
我按照你的教程修改splayerx播放器，但是总是失败

### ISSUE THREAD

**Issue by zijiren233** [liyang5945/sync-player#6]
![image](https://user-images.githubusercontent.com/84728412/156767579-0a46677f-18ef-4444-a42f-e21bf2af82a8.png)
总是提示这个，不知道该怎么办

**Comment by zijiren233** [comment]
![image](https://user-images.githubusercontent.com/84728412/156767753-3b66b016-8ddf-4914-ae61-d76ead024ab8.png)
这个是workflow文件

**Comment by liyang5945** [comment]
看起来是安装依赖出了问题，安装依赖时要翻墙的，不翻墙绝对安装不成功

**Comment by zijiren233** [comment]
我用的是github的workflow呀，github的机器应该不存在翻墙问题，而且第一步只添加依赖的时候是可以安装成功的。但是进行后续的修改后才失败的

**Comment by zijiren233** [comment]
[https://github.com/zijiren233/splayerx](https://github.com/zijiren233/splayerx)
这个是我修改后的项目地址，我先测试过只添加依赖并安装，是可以通过的，但是添加了一个随机数的函数后就无法通过了

**Comment by liyang5945** [comment]
> https://github.com/zijiren233/splayerx 这个是我修改后的项目地址，我先测试过只添加依赖并安装，是可以通过的，但是添加了一个随机数的函数后就无法通过了

github workflow我没测试过，等下我fork一个试下

**Comment by zijiren233** [comment]
好的感谢~~~ 从 Windows 版邮件发送 发件人: liyang5945发送时间: 2022年3月7日 14:21收件人: liyang5945/sync-player抄送: zijiren233; Author主题: Re: [liyang5945/sync-player] 我按照你的教程修改splayerx播放器，但是总是失败 (Issue #6) https://github.com/zijiren233/splayerx 这个是我修改后的项目地址，我先测试过只添加依赖并安装，是可以通过的，但是添加了一个随机数的函数后就无法通过了github workflow我没测试过，等下我fork一个试下—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by zijiren233** [comment]
感谢~~~

**Comment by liyang5945** [comment]
> 感谢~~~
我fork的可以build成功了，应该是代码校验规则的问题，原文档` 使用 eslint 控制代码质量，不满足标准的代码无法通过编译并会报错`，我写的代码没有按照他的规则，把规则校验去掉就能成功

**Comment by zijiren233** [comment]
感谢~~！！

**Comment by zijiren233** [comment]
是否有考虑加一个倍速功能

**Comment by zijiren233** [comment]
编译出来有BUG，无法拖动窗口位置

**Comment by zijiren233** [comment]
经测试，在我什么都没改，直接编译的情况下，都是有这个bug的，就是窗口无法拖动

**Comment by liyang5945** [comment]
> 经测试，在我什么都没改，直接编译的情况下，都是有这个bug的，就是窗口无法拖动

倍速功能播放器已经自带了，如果没有你想要的播放速度，可以在这个文件里修改：/containers/AdvanceMainMenu.vue 272行，无法拖动窗口位置这个是源码的bug，我fork的已经修复

**Comment by zijiren233** [comment]
> > 经测试，在我什么都没改，直接编译的情况下，都是有这个bug的，就是窗口无法拖动
> 
> 倍速功能播放器已经自带了，如果没有你想要的播放速度，可以在这个文件里修改：/containers/AdvanceMainMenu.vue 272行，无法拖动窗口位置这个是源码的bug，我fork的已经修复

我指的是倍速也能同步到所有客户端

**Comment by zijiren233** [comment]
还有一个小问题就是怎么用射手影音自带播放器播放http直链的视频，因为如果是再射手影音里用网页打开视频，是不会调用射手影音自带的播放器播放，就不会调用同步播放模块

**Comment by loukai99** [comment]
我参考作者的方法改好并发布了release版本，你可以直接下载填入leancloud的信息直接使用。[shareplay-video-player](https://github.com/loukai99/shareplay-video-player/releases)

**Comment by zijiren233** [comment]
能否添加改进web版本点击视频播放器内的按钮也可以实现同步，而不是必须点外部的按钮才可以同步
